CREATE TABLE current_state (ID BIGINT NOT NULL, TYPE VARCHAR(255) NOT NULL, AS_OF TIMESTAMP NOT NULL, STATE VARCHAR(255) NOT NULL, PRIMARY KEY (ID, TYPE));
CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID TINYINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
