ALTER TABLE WEBSERVER ADD COLUMN HTTPCONFIGFILE VARCHAR(255);
UPDATE WEBSERVER SET HTTPCONFIGFILE = 'D:/apache/httpd-2.4.9/conf/httpd.conf';
ALTER TABLE WEBSERVER ALTER COLUMN HTTPCONFIGFILE SET NOT NULL;