ALTER TABLE WEBSERVER ADD STATUSPATH VARCHAR(255);
UPDATE WEBSERVER SET STATUSPATH = '/jk/status';
ALTER TABLE WEBSERVER ALTER COLUMN STATUSPATH SET NOT NULL;
ALTER TABLE JVM_CONTROL_HISTORY ALTER COLUMN RETURNERROROUTPUT VARCHAR(1048576);
ALTER TABLE JVM_CONTROL_HISTORY ALTER COLUMN RETURNOUTPUT VARCHAR(1048576);