/** @jsx React.DOM */
var Anchor = React.createClass({
    render: function() {

        /**
         * We use JQuery event binding so that its onClick event will run even when it is generated by
         * React's renderComponentToString or renderComponentToStaticMarkup.
         */
        $("#" + this.props.id).off("click");
        $("#" + this.props.id).on("click", this.linkClick);

        /**
         * Use button element since the link element and all other HTML elements (except button) and their attributes
         * show up in the filter. This is a shortcoming of jQuery Datatable 1.9.4. Please see
         * http://datatables.net/forums/discussion/20831/exclude-html-contents-classes-from-text-search.
         */
        return <button id={this.props.id} className="button-link">{this.props.value}</button>
    },
    linkClick: function() {
        if ($("#" + this.props.id).hasClass("disabled")) {
            return false;
        }

        if (this.props.waitForResponse === true) {
            this.props.callback("#" + this.props.id, this.props.data);
        } else {
            this.props.callback(this.props.data);
        }

        return false;
    }
});
