/** @jsx React.DOM */
var Anchor = React.createClass({
    render: function() {

        /**
         * We use JQuery event binding so that its onClick event will run even when it is generated by
         * React's renderComponentToString or renderComponentToStaticMarkup.
         */
        $("#" + this.props.id).off("click");
        $("#" + this.props.id).on("click", this.linkClick);

        return <a id={this.props.id} href="">{this.props.value}</a>
    },
    linkClick: function() {
        this.props.callback(this.props.data);
        return false;
    }
});
