#!/bin/sh

### BEGIN INIT INFO
# Provides:          tomcat
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop Apache Tomcat
# Description:       Enable Apache Tomcat service provided by daemon.
# chkconfig: 2345 99
### END INIT INFO

# $1=/opt/ctp/app/apache-tomcat-7.0.55
ECHO=/bin/echo
TOMCAT_HOME=$1
TOMCAT_HOME_BIN=$TOMCAT_HOME/bin
TOMCAT_USER=z002s9mw

# For SELinux we need to use 'runuser' not 'su'
if [ -x "/sbin/runuser" ]; then
    SU="/sbin/runuser -s /bin/sh"
else
    SU="/bin/su -s /bin/sh"
fi

start() {
    $ECHO -n "Starting Tomcat Jwala "
    $SU - $TOMCAT_USER -c "pushd $TOMCAT_HOME_BIN; sudo ./startup.sh; popd"
    $ECHO "."
}

stop() {
    $ECHO -n "Stopping Tomcat Jwala "
    $SU - $TOMCAT_USER -c "pushd $TOMCAT_HOME_BIN; sudo ./catalina.sh stop 20 -force; popd"
    $ECHO "."
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 15
        start
        ;;
    *)
        $ECHO "Usage: tomcat {start|stop|restart}"
        exit 1
esac
exit 0
