DROP TABLE grp;
DROP TABLE GRP_JVM;
DROP TABLE jvm;
DROP TABLE webserver;
DROP TABLE WEBSERVER_GRP;
DROP TABLE jvm_control_history;
DROP TABLE webserver_control_history;
DROP TABLE CURRENT_JVM_STATE;

DROP TABLE PUBLIC.APP;
DROP TABLE PUBLIC.GRP;
DROP TABLE PUBLIC.GRP_JVM;
DROP TABLE PUBLIC.JVM;
DROP TABLE PUBLIC.WEBSERVER;
DROP TABLE PUBLIC.WEBSERVER_GRP;
